export default [{
  title: 'Leave the road T-shirt',
  image: '1.png',
  images: ['1.png', '2.png', '3.png', '4.png', '5.png'],
  price: 25,
  priceCompare: null,
  rating: 4,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}, {
  title: 'Creative T-Shirt',
  image: '2.png',
  images: ['2.png', '6.png', '3.png', '4.png', '5.png'],
  price: 22,
  priceCompare: 30,
  rating: 3,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}, {
  title: 'That T-Shirt',
  image: '3.png',
  images: ['3.png', '1.png', '6.png', '4.png', '5.png'],
  price: 25,
  priceCompare: null,
  rating: 4,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}, {
  title: 'Skeleton T-Shirt',
  image: '4.png',
  images: ['4.png', '2.png', '3.png', '6.png', '5.png'],
  price: 24,
  priceCompare: null,
  rating: 4,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}, {
  title: 'Dragonball T-Shirt',
  image: '5.png',
  images: ['5.png', '2.png', '3.png', '4.png', '6.png'],
  price: 26,
  priceCompare: 33,
  rating: 4,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}, {
  title: 'Black T-Shirt',
  image: '6.png',
  images: ['6.png', '2.png', '3.png', '4.png', '5.png'],
  price: 23,
  priceCompare: null,
  rating: 3,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}, {
  title: 'Grey T-Shirt',
  image: '7.png',
  images: ['7.png', '2.png', '3.png', '4.png', '5.png'],
  price: 26,
  priceCompare: 34,
  rating: 0,
  reviews: []
}, {
  title: 'F* Awesome T-Shirt',
  image: '8.png',
  images: ['8.png', '2.png', '3.png', '4.png', '5.png'],
  price: 27,
  priceCompare: 32,
  rating: 4,
  reviews: [{ 'name':'Joellen','rating':4,'review':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.' },
    { 'name':'Griz','rating':3,'review':'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.' },
    { 'name':'Paddy','rating':5,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Kaela','rating':3,'review':'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.' },
    { 'name':'Verina','rating':4,'review':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.' },
    { 'name':'Lonnard','rating':3,'review':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.' }]
}]
